# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_normalization/rpc/text_normalization.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="text_normalization/rpc/text_normalization.proto",
    package="",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=b'\n/text_normalization/rpc/text_normalization.proto\x1a\x19google/protobuf/any.proto"M\n\tTNRequest\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\x17\n\x08\x61\x64vanced\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x19\n\nparse_ssml\x18\x03 \x01(\x08:\x05\x66\x61lse"\x1a\n\nTNResponse\x12\x0c\n\x04text\x18\x01 \x02(\t2:\n\x12text_normalization\x12$\n\tnormalize\x12\n.TNRequest\x1a\x0b.TNResponse',
    dependencies=[
        google_dot_protobuf_dot_any__pb2.DESCRIPTOR,
    ],
)


_TNREQUEST = _descriptor.Descriptor(
    name="TNRequest",
    full_name="TNRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="text",
            full_name="TNRequest.text",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="advanced",
            full_name="TNRequest.advanced",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=True,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="parse_ssml",
            full_name="TNRequest.parse_ssml",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=True,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=155,
)


_TNRESPONSE = _descriptor.Descriptor(
    name="TNResponse",
    full_name="TNResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="text",
            full_name="TNResponse.text",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=157,
    serialized_end=183,
)

DESCRIPTOR.message_types_by_name["TNRequest"] = _TNREQUEST
DESCRIPTOR.message_types_by_name["TNResponse"] = _TNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TNRequest = _reflection.GeneratedProtocolMessageType(
    "TNRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _TNREQUEST,
        "__module__": "text_normalization.rpc.text_normalization_pb2"
        # @@protoc_insertion_point(class_scope:TNRequest)
    },
)
_sym_db.RegisterMessage(TNRequest)

TNResponse = _reflection.GeneratedProtocolMessageType(
    "TNResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _TNRESPONSE,
        "__module__": "text_normalization.rpc.text_normalization_pb2"
        # @@protoc_insertion_point(class_scope:TNResponse)
    },
)
_sym_db.RegisterMessage(TNResponse)


_TEXT_NORMALIZATION = _descriptor.ServiceDescriptor(
    name="text_normalization",
    full_name="text_normalization",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=185,
    serialized_end=243,
    methods=[
        _descriptor.MethodDescriptor(
            name="normalize",
            full_name="text_normalization.normalize",
            index=0,
            containing_service=None,
            input_type=_TNREQUEST,
            output_type=_TNRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_TEXT_NORMALIZATION)

DESCRIPTOR.services_by_name["text_normalization"] = _TEXT_NORMALIZATION

# @@protoc_insertion_point(module_scope)
